# Generated by Django 4.2.5 on 2023-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
