# Generated by Django 4.2.5 on 2023-09-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='follow',
        ),
    ]
