# Generated by Django 4.2.5 on 2023-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_followmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmodel',
            name='is_followed',
            field=models.BooleanField(default=True),
        ),
    ]
